### ISSUE TITLE
export data

### ISSUE THREAD

**Issue by djlauk** [paulscherrerinstitute/databuffer-ui#71]
- [x] Implement download of data #17 
- [x] Add convenience function: copy curl command #69 
- [x] Write documentation for downloading data #70
